name: "Bug Report"
description: "Report a bug if something isn't working as expected in SuperWebShare"
title: "[Bug]: "
labels: ["status/awaiting_triage"]
assignees:
  - josevarghese
body:
  - type: markdown
    attributes:
      value: |
        ## BEFORE POSTING YOUR ISSUE

        - Please create GitHub issues only for SuperWebShare bugs. GitHub issues ARE NOT FOR SUPPORT.

        - To avoid duplicates, please search this repository for the issue.

        - Ensure you are using the most updated versions of SuperWebShare, WordPress & your theme.

        Deactivate all of your plugins. If this solves the problem, gradually activate each plugin until you spot the problematic one.

        - Change your WordPress theme to [default WordPress theme](https://wordpress.org/themes/twentytwentyfour/).

        ## THE ISSUE
  - type: checkboxes
    id: prerequisites
    attributes:
      label: "Prerequisites"
      options:
        - label: "I've read and understood the [contribution guidelines](https://github.com/superwebshare/super-web-share/blob/trunk/.github/CONTRIBUTING.md)."
          required: true
        - label: "I've searched for related issues and avoided creating a duplicate issue."
          required: true
  - type: textarea
    id: description
    validations:
      required: true
    attributes:
      label: "Description"
      description: "Describe the problem. What caused the issue? What did you expect to happen, and what happened? Please be as descriptive as possible. Attach screenshots and related links (if possible)."
  - type: textarea
    id: steps_to_reproduce
    validations:
      required: true
    attributes:
      label: "Steps to reproduce"
      description: "List all the steps needed to reproduce the issue so we can replicate it ourselves."
      placeholder: "1) .... 2) ... 3) ..."
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so there is no need for backticks.
      render: shell
  - type: checkboxes
    id: isolating_the_problem
    attributes:
      label: "Isolating the problem"
      options:
        - label: "This bug happens only when the SuperWebShare plugin is active."
        - label: "This bug happens with a default WordPress theme ([Twenty Twenty Four theme](https://wordpress.org/themes/twentytwentyfour/))."
        - label: "I can reproduce this bug consistently using the steps above."
