blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://superwebshare.com/contact/
    about: Customer experience for SuperWebShare users who are having questions or seeking general support.
  - name: Documentation
    url: https://superwebshare.com/docs/
    about: Information and documentation about Super Web Share.
