name: ✨ Feature request
description: If you have suggestions for improving existing functionality or require something for development (such as a new hook), please let us know or consider submitting a Pull Request!
title: "[Feature request]: "
labels: ["type: feature-request"]
body:
  - type: markdown
    attributes:
      value: |
        ### WooHoo!!! Thanks for contributing!

        Before opening a new issue, please search for duplicate issues to prevent opening a duplicate feature request. If there is already an open existing request, please leave a comment there.
    id: summary
    attributes:
        label:  Is your feature request related to a problem? Please describe.
        description: A clear and concise description of what you want to see within the plugin
    validations:
      required: true
  - type: textarea
    id: alternative
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of the solution
  - type: textarea
    id: context
    attributes:
      label: Why do you think this feature is something we should consider for the Super Web Share plugin?
      description: It will help us to prioritize the issue.
